session_name: esl
start_directory: ~/dev/_html/esl
windows:
  - window_name: gulp
    layout: main-vertical
    panes:
      - npm run gulp
      -
  - window_name: todo
    layout: main-vertical
    focus: true
    panes:
      - nvim TODO.tasks
      - /usr/bin/open -a "/Applications/Google Chrome Canary.app" 'http://localhost:9000'
  - window_name: editor
    panes:
      - nvim .
