session_name: esl
start_directory: ~/dev/_html/esl
windows:
  - window_name: gulp
    layout: main-vertical
    panes:
      - gulp server
      - gulp build && gulp watch
  - window_name: todo
    layout: main-vertical
    focus: true
    panes:
      - nvim TODO.tasks
      - /usr/bin/open -a "/Applications/Google Chrome.app" 'http://localhost:9000' && nvim ~/notes/esl.md
  - window_name: editor
    panes:
      - nvim .
