#!/bin/bash
echo "Deploying fortedefence.com..."

gulp build
BUILD_FOLDER=build
rm -f $BUILD_FOLDER/img/*
cp -f assets/images/* $BUILD_FOLDER/img/
cp -f .bitballoon $BUILD_FOLDER
cd $BUILD_FOLDER
bitballoon deploy || exit 1
cd ..

echo "> Deploy completed!"
